name: Deploy Db Layer to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push db-layer image
        uses: docker/build-push-action@v5
        with:
          context: ./DbAccessor
          file: ./DbAccessor/Dockerfile
          push: true
          tags: dhairyahp15/db-layer:latest
